#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# Start Quickshell
qs -c ~/dotfiles/.config/quickshell/ii/ &

# albert
nohup albert > /dev/null 2>&1 &

# notification daemon
dunst &

$scripts/tools/dynamic &

# wallpaper
$scripts/wall $config/wallpapers/cloud.png &

# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &